In [1]:
import numpy as np

In [2]:
# 1. tạo 2 ma trận ngẫu nhiên 3x3
A = np.array([[2, 7, 5],
              [1, 2, 4],
              [4, 8, 9]])
B = np.array([[2, 2, 4],
              [3, 5, 8],
              [1, 3, 3]])

In [3]:
# 2. tổng 2 ma trận
print(A+B)

[[ 4  9  9]
 [ 4  7 12]
 [ 5 11 12]]


In [4]:
# 3. hiệu ma trận A-B
print(A-B)

[[ 0  5  1]
 [-2 -3 -4]
 [ 3  5  6]]


In [5]:
# 4. tích thông thường
print(A.dot(B))

[[ 30  54  79]
 [ 12  24  32]
 [ 41  75 107]]


In [6]:
# 5. tích Hadamard
print(A*B)

[[ 4 14 20]
 [ 3 10 32]
 [ 4 24 27]]


In [7]:
# 6. định thức ma trận A
print(np.linalg.det(A))

21.0


In [48]:
# 7. tính nghịch đảo của A
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.66666667 -1.0952381   0.85714286]
 [ 0.33333333 -0.0952381  -0.14285714]
 [ 0.          0.57142857 -0.14285714]]


In [9]:
# 8. tính chuyển vị của A
print(A.T)

[[2 1 4]
 [7 2 8]
 [5 4 9]]


In [10]:
# 9. tính ma trận giả nghịch đảo của A
print(np.linalg.pinv(A))

[[-6.66666667e-01 -1.09523810e+00  8.57142857e-01]
 [ 3.33333333e-01 -9.52380952e-02 -1.42857143e-01]
 [ 3.56540718e-17  5.71428571e-01 -1.42857143e-01]]


In [11]:
# 10. tính Frobenius norm của A
print(np.linalg.norm(A))

16.1245154965971


In [22]:
# 11. 
# Norm L1 mỗi hàng trong A
row1_norm1 = np.linalg.norm(A[0,:], 1)
row2_norm1 = np.linalg.norm(A[1,:], 1)
row3_norm1 = np.linalg.norm(A[2,:], 1)
print(row1_norm1)
print(row2_norm1)
print(row3_norm1)

# Norm L2 mỗi hàng trong A
row1_norm2 = np.linalg.norm(A[0,:], 2)
row2_norm2 = np.linalg.norm(A[1,:], 2)
row3_norm2 = np.linalg.norm(A[2,:], 2)
print(row1_norm2)
print(row2_norm2)
print(row3_norm2)

14.0
7.0
21.0
8.831760866327848
4.58257569495584
12.68857754044952


In [38]:
# 12. ma trận con 2x2 góc trên trái A
A_2x2_left = A[0:2, 0:2]
print(A_2x2_left)

[[2 7]
 [1 2]]


In [39]:
# 13. nhân vô hướng A với a=2
print(A*2)

[[ 4 14 10]
 [ 2  4  8]
 [ 8 16 18]]


In [47]:
# 14. Tính ma trận đối xứng ATA
print(A.T.dot(A))

[[ 21  48  50]
 [ 48 117 115]
 [ 50 115 122]]


In [42]:
# 15. Tính trace A
print(np.linalg.trace(A))

13


In [52]:
# 16.
eigen_values, eigen_vectors = np.linalg.eig(A)

# tìm các giá trị riêng
eigen_value_1 = eigen_values[0]
eigen_value_2 = eigen_values[1]
eigen_value_3 = eigen_values[2]
print(eigen_value_1)
print(eigen_value_2)
print(eigen_value_3)

# tìm các vector riêng
eigen_vector_1 = eigen_vectors[0]
eigen_vector_2 = eigen_vectors[1]
eigen_vector_3 = eigen_vectors[2]
print(eigen_vector_1)
print(eigen_vector_2)
print(eigen_vector_3)


(14.41873967083326+0j)
(-0.7093698354166313+0.9763362182309253j)
(-0.7093698354166313-0.9763362182309253j)
[ 0.49759993+0.j -0.86586104+0.j -0.86586104-0.j]
[0.30197734+0.j         0.24297125-0.31602757j 0.24297125+0.31602757j]
[0.81314451+0.j        0.12902781+0.2733643j 0.12902781-0.2733643j]


In [80]:
# 17. 
# Kiểm tra A có khả năng chéo hóa hay không
if np.linalg.matrix_rank(eigen_vectors) == A.shape[0]:
    print("A có thể chéo hóa")
else:
    print("A không thể chéo hóa được")

# tính ma trận chéo hóa A
A_diagonalize = np.linalg.inv(eigen_vectors).dot(A).dot(eigen_vectors)
print(A_diagonalize)

A có thể chéo hóa
[[ 1.44187397e+01+5.14778475e-17j -1.16191760e-15-1.84563208e-15j
  -1.19573536e-15+1.82410027e-15j]
 [ 1.22933117e-15-5.03798827e-15j -7.09369835e-01+9.76336218e-01j
   2.22044605e-16+1.66533454e-16j]
 [ 9.93265663e-16+3.72589332e-15j  3.33066907e-16-1.11022302e-16j
  -7.09369835e-01-9.76336218e-01j]]


In [71]:
# 18. tạo ma trận C 3x3 toàn 1 và cộng với A
C = np.full((3,3), 1)
print(C)
print(A+C)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 3  8  6]
 [ 2  3  5]
 [ 5  9 10]]


In [59]:
# 19. tạo ma trận chéo từ 1 vector kích thước 3 ngẫu nhiên
z = np.array([1, 2, 3])
Z = np.diag(z)
print(Z)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [65]:
# 20. kiểm tra ma trận A có phải ma trận trực giao không
if np.linalg.det(A.dot(A.T)) == 0:
    print("A là ma trận trực giao")
else:
    print("A không phải ma trận trực giao")

A không phải ma trận trực giao


In [66]:
# 21. tạo ma trận 4x4 ngẫu nhiên
D = np.array([[1, 4, 2, 5],
             [2, 7, 2, 1],
             [3, 5, 2, 1],
             [1, 2, 3, 6]])

In [68]:
# 22. tính ma trận nghịch đảo của D
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.32727273 -0.63636364  0.74545455 -0.29090909]
 [ 0.16363636  0.18181818 -0.12727273 -0.14545455]
 [-1.12727273  0.63636364 -0.34545455  0.89090909]
 [ 0.45454545 -0.27272727  0.09090909 -0.18181818]]


In [75]:
# 23. 
# tính ma trận D nhân chính nó
DxD = D.dot(D)
print(DxD)

# so sánh DxD và DxD^-1
DxD_inv = D.dot(D_inv)
if np.allclose(DxD, DxD_inv):
    print("2 ma trận bằng nhau")
else:
    print("2 ma trận khác nhau")

[[20 52 29 41]
 [23 69 25 25]
 [20 59 23 28]
 [20 45 30 46]]
2 ma trận khác nhau


In [76]:
# 24. 
# tính ma trận d = ATxBxA
d = A.T.dot(B).dot(A)
print(d)

# tìm định thức của d
print(np.linalg.det(d))

[[ 155  343  391]
 [ 376  836  944]
 [ 435  963 1094]]
-1763.9999999999095


In [77]:
# 26. tính tổng ma trận D với ma trận đơn vị I4 kích thước 4
I4 = np.eye(4)
print(D+I4)

[[2. 4. 2. 5.]
 [2. 8. 2. 1.]
 [3. 5. 3. 1.]
 [1. 2. 3. 7.]]


In [79]:
# 27. tạo ma trận F ngẫu nhiên và có đường chéo là các phần tử của 1 vector ngẫu nhiên
F = np.array([[1, 2, 5],
              [2, 4, 2],
              [1, 5, 3]])
f = np.array([9, 9, 9])
np.fill_diagonal(F, f)
print(F)

[[9 2 5]
 [2 9 2]
 [1 5 9]]


In [83]:
# 28. Kiểm tra ma trận F có chéo hóa được không
eigen_values, eigen_vectors = np.linalg.eig(F)

if np.linalg.matrix_rank(eigen_vectors) == F.shape[0]:
    print("A có thể chéo hóa")
else:
    print("A không thể chéo hóa được")

A có thể chéo hóa


In [81]:
# 29. Kiểm tra ma trận F có phải ma trận chéo không
if np.all(F == np.diag(np.diag(F))):
    print("F là ma trận chéo")
else:
    print("F không phải ma trận chéo")

F không phải ma trận chéo hóa.


In [82]:
# 30. tính trace F
print(np.trace(F))

27
